# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haterz', '0002_auto_20180802_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_for_me', to='haterz.User'),
        ),
    ]
